### ISSUE TITLE
Recompile for unified api?

### ISSUE THREAD

**Issue by Corstiaan84** [neilkennedy/FontAwesome.Xamarin#2]
Hi :-).

This looks really cool! However, I get the following error when trying to compile my project:

Error MT0034: Cannot include both 'monotouch.dll' and 'Xamarin.iOS.dll' in the same Xamarin.iOS project - 'Xamarin.iOS.dll' is referenced explicitly, while 'monotouch.dll' is referenced by 'FontAwesome.Xamarin, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. (MT0034) (Reflect.Mobile.iOS)

Based on a little research I have learned that the build build of FontAwesome.Xamarin does not work with the unified iOS api. I tried recompiling the source but no luck so far. Any ideas?

Thanks for this project!

**Comment by neilkennedy** [comment]
Hi,

I'm guessing this project was compiled  against an old version of Xamarin and they've updated the DLL that's referenced now. I no longer have a Xamarin license (or a Mac for that matter) so I can't try and recompile it myself.

There are only a couple of class files in here, so you could potentially create a brand new empty Xamarin project and manually copy in my class files. Hopefully that should work.

If you do manage to get it working, feel free to send a pull request and I'll merge it in.

Neil

**Comment by neilkennedy** [comment]
I jut had a look at the forks for this and it seems like someone has made it compatible with the a version of Xamarin.iOS from January of this year. Might be worth checking it out.

https://github.com/studiomobile/FontAwesome.Xamarin

**Comment by Corstiaan84** [comment]
https://github.com/studiomobile/FontAwesome.Xamarin

This one worked. Thanks!

**Comment by neilkennedy** [comment]
No problem. Seems like that version is vastly improved over my one so the examples in the ReadMe won't work any more. It doesn't look like he updated his ReadMe either so you might need to play around with it to figure out how it works
